### ISSUE TITLE
Get upload to chain stuff working

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-core#190] opened 2017-06-20 23:18 UTC

**Comment by joeykrug** [comment] 2017-10-03 05:13
@adrake can you add a description of how to use the deployment script to readme then we can close this?

**Comment by adrake33** [comment] 2017-10-03 05:24
Sure, I'll add a description for how to use it to the readme tomorrow morning.  I'm still working on an integration test to verify everything is getting deployed as expected, though.  (That is, the contracts are getting added to the controller & delegated correctly, etc.  The test will basically create a market, place a trade, and go through reporting.)  Should I wait to close it until the test is confirmed to be working?  I'm guessing it may take another day or two before I can confirm that everything looks correct.

**Comment by joeykrug** [comment] 2017-10-03 14:41
Sure just close it then

**Closed** 2017-10-22 21:26 UTC

**Comment by adrake33** [comment] 2017-10-22 22:14
Just to clarify, the deployment script is only working with Parity on a private chain at the moment. 
 There's still more work to be done with the deployment script, including:

1. Get market creation working in Geth.
2. Get the whole process working against Rinkeby & Kovan.
3. Get the whole process working against Ropsten.
4. Convert the script to be called as a library rather than a CLI app.
5. Design automated deployment system: targeting Rinkeby, Kovan, Ropsten, Foundation; include script to commit to `augur-contracts/master`.
6. Implement automated deployment system.
7. Setup automated build server that deploys to Rinkeby & Kovan on push to `augur-core/develop`.
8. Setup automated build server that deploys to Ropsten or Foundation on manual trigger.
9. Author more full-featured integration test suite.

I believe Micah said he was going to create Clubhouse tickets for these tasks, but I just wanted to make sure you were aware of these things that are still pending, @joeykrug.

**Comment by joeykrug** [comment] 2017-10-22 22:16
What is `Foundation`? And yeah closed b/c I saw that it was moving to clubhouse tickets ^^

**Comment by adrake33** [comment] 2017-10-22 22:21
I believe `Foundation` may be the name of a private chain we'll be using internally.  Is that correct, @MicahZoltu?

**Comment by MicahZoltu** [comment] 2017-10-23 00:03
Foundation is the name of the chain colloquially referred to as "main network".

Since all other chains have a name _except_ that one, and to avoid providing undue weight on the feature set pushed by the Ethereum Foundation (since that isn't decentralized consensus) there is a community movement to name it Foundation.  Parity UI now refers to it as "Ethereum network launched by the Ethereum Foundation" and internally they refer to it as "Foundation".
